name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        npm install -g html-minifier-terser
        npm install -g clean-css-cli
        npm install -g uglify-js
        
    - name: Optimize files
      run: |
        # Minify HTML files
        find docs -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true -o {} {} \;
        
        # Minify CSS files
        find docs -name "*.css" -exec cleancss -o {} {} \;
        
        # Minify JavaScript files
        find docs -name "*.js" -exec uglifyjs {} -o {} \;
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs 